apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default  # Ajout du namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: backend
        image: akasbiacrpfa.azurecr.io/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "db"
        - name: MYSQL_DATABASE
          value: "templates"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "yasser1234"
