apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: frontend
        image: akasbiacrpfa.azurecr.io/frontend:latest
        ports:
        - containerPort: 3000
